twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # création des namespaces css et templates utilisés pour les emails
        '%kernel.project_dir%/public/css/emails':   email_css
        '%kernel.project_dir%/templates/email':     email_templates
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true